
#ifndef C_LIGHTSTRIPS_H
#define C_LIGHTSTRIPS_H

#define DDR_LIGHTSTRIP_DATA
#define PORT_LIGHTSTRIP_DATA
#define MASK_LIGHTSTRIP_DATA
#define HANDLER_LIGHTSTRIP_DATA &Handler_LightStripData

void Handler_LightStripData (struct DigitalComponent comp);



#define DDR_LIGHTSTRIP_EMPHASISR
#define PORT_LIGHTSTRIP_EMPHASISR
#define MASK_LIGHTSTRIP_EMPHASISR


#define DDR_LIGHTSTRIP_EMPHASISG
#define PORT_LIGHTSTRIP_EMPHASISG
#define MASK_LIGHTSTRIP_EMPHASISG


#define DDR_LIGHTSTRIP_EMPHASISB
#define PORT_LIGHTSTRIP_EMPHASISB
#define MASK_LIGHTSTRIP_EMPHASISB





#define DDR_LIGHTSTRIP_BACKGROUNDR
#define PORT_LIGHTSTRIP_BACKGROUNDR
#define MASK_LIGHTSTRIP_BACKGROUNDR


#define DDR_LIGHTSTRIP_BACKGROUNDG
#define PORT_LIGHTSTRIP_BACKGROUNDG
#define MASK_LIGHTSTRIP_BACKGROUNDG


#define DDR_LIGHTSTRIP_BACKGROUNDB
#define PORT_LIGHTSTRIP_BACKGROUNDB
#define MASK_LIGHTSTRIP_BACKGROUNDB

#endif
