
#ifndef DIGITALCOMPONENTS_H
#define DIGITALCOMPONENTS_H

#include "../Registers.h"

////////////////////////////
// Add Digital Components //
////////////////////////////
#include "Digital/LightStrips.h"

/////////////////////////////////
// Register Digital Components //
/////////////////////////////////
#define COMPONENTLIST_DIGITAL   InitializeOComponent(Digital, REGID_LIGHTSTRIPS_ERED, DDR_LIGHTSTRIP_EMPHASISR, PORT_LIGHTSTRIP_EMPHASISR, MASK_LIGHTSTRIP_EMPHASISR, HANDLER_LIGHTSTRIP_EMPHASISR), \
                                InitializeOComponent(Digital, REGID_LIGHTSTRIPS_EGREEN, DDR_LIGHTSTRIP_EMPHASISG, PORT_LIGHTSTRIP_EMPHASISG, MASK_LIGHTSTRIP_EMPHASISG, HANDLER_LIGHTSTRIP_EMPHASISG), \
                                InitializeOComponent(Digital, REGID_LIGHTSTRIPS_EBLUE, DDR_LIGHTSTRIP_EMPHASISB, PORT_LIGHTSTRIP_EMPHASISB, MASK_LIGHTSTRIP_EMPHASISB, HANDLER_LIGHTSTRIP_EMPHASISB), \
                                InitializeOComponent(Digital, REGID_LIGHTSTRIPS_BRED, DDR_LIGHTSTRIP_BACKGROUNDR, PORT_LIGHTSTRIP_BACKGROUNDR, MASK_LIGHTSTRIP_BACKGROUNDR, HANDLER_LIGHTSTRIP_BACKGROUNDR), \
                                InitializeOComponent(Digital, REGID_LIGHTSTRIPS_BGREEN, DDR_LIGHTSTRIP_BACKGROUNDG, PORT_LIGHTSTRIP_BACKGROUNDG, MASK_LIGHTSTRIP_BACKGROUNDG, HANDLER_LIGHTSTRIP_BACKGROUNDG), \
                                InitializeOComponent(Digital, REGID_LIGHTSTRIPS_BBLUE, DDR_LIGHTSTRIP_BACKGROUNDB, PORT_LIGHTSTRIP_BACKGROUNDB, MASK_LIGHTSTRIP_BACKGROUNDB, HANDLER_LIGHTSTRIP_BACKGROUNDB), \
                                InitializeOComponent(Digital, 0x00, DDR_LIGHTSTRIP_DATA, PORT_LIGHTSTRIP_DATA, MASK_LIGHTSTRIP_DATA, HANDLER_LIGHTSTRIP_DATA)

#define COMPONENTLIST_DIGITAL_COUNT 7

#endif
