
#ifndef SHIFTREGISTERS_H
#define SHIFTREGISTERS_H

#define SHIFTREGISTER_EMPHASIS_R
#define SHIFTREGISTER_EMPHASIS_G
#define SHIFTREGISTER_EMPHASIS_B

#define SHIFTREGISTER_SUPPORT_R
#define SHIFTREGISTER_SUPPORT_G
#define SHIFTREGISTER_SUPPORT_B

#define SHIFTREGISTER_EMPHASIS_SELECT
#define SHIFTREGISTER_SUPPORT_SELECT



#define SHIFTREGISTER_EMPHASIS_PORT
#define SHIFTREGISTER_EMPHASIS_REG

#define SHIFTREGISTER_SUPPORT_PORT
#define SHIFTREGISTER_SUPPORT_REG

#endif
