
#ifndef CONFIG_H
#define CONFIG_H

#define CONFIG_CONTROLLER_STANDBYTIMEOUT 0.25

#define CONFIG_COMMUNICATIONS_MODEMASK 0x80
#define CONFIG_COMMUNICATIONS_READMODE 0x00
#define CONFIG_COMMUNICATIONS_WRITEMODE 0x80

#define CONFIG_PRESETS_CALLBACKPERIOD 0.005
#define CONFIG_PRESETS_PERSISTMASK 0x80



#define CONFIG_F_CPU 16000000UL

#endif
